api = "0.7"

[buildpack]
  id = "ninech/buildpack-rails-permissions"
  homepage = "https://github.com/ninech/buildpack-rails-permissions"
  name = "Rails-Permissions Buildpack"
  version = "0.0.1"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[metadata]
  include-files = ["bin/run","bin/build","bin/detect","buildpack.toml"]
  pre-package = "./scripts/build.sh"
